// flow-typed signature: 7cf7307e7ea8ba862e820c6aa70be55a
// flow-typed version: <<STUB>>/react-bounds_v^0.3.1/flow_v0.43.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-bounds/build/bundle' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/components/Home' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/components/home/Docs' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/components/home/Features' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/components/home/Footer' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/components/home/Header' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/components/home/Hero' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/components/home/Tweet' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/documentation/index' {
  declare module.exports: any;
}

declare module 'react-bounds/docs/index' {
  declare module.exports: any;
}

declare module 'react-bounds/examples/Box' {
  declare module.exports: any;
}

declare module 'react-bounds/examples/Outside' {
  declare module.exports: any;
}

declare module 'react-bounds/examples/schedule/Schedule' {
  declare module.exports: any;
}

declare module 'react-bounds/examples/schedule/ScheduleItem' {
  declare module.exports: any;
}

declare module 'react-bounds/gulpfile' {
  declare module.exports: any;
}

declare module 'react-bounds/lib/index' {
  declare module.exports: any;
}

declare module 'react-bounds/lib/listener' {
  declare module.exports: any;
}

declare module 'react-bounds/lib/Wrap' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/highlight' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/highlight.js/highlight' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/highlight.js/index' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/highlight.js/languages/javascript' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-basic-layout/index' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-basic-layout/src/components/Container' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-basic-layout/src/components/Grid' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/index' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/src/components/Code' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/src/components/Docs' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/src/components/Markdown' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/src/components/MarkdownTitle' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/src/components/Sidebar' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/src/components/SidebarItem' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-docs/src/helpers/markdown' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/index' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/lib/components/Link' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/lib/components/Raised' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/lib/components/Tab' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/lib/components/Tabs' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/lib/components/Tile' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/src/components/Link' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/src/components/Raised' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/src/components/Tab' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/src/components/Tabs' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-material-design/src/components/Tile' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-move/index' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-move/lib/components/Move' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/react-move/src/components/Move' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/remarkable/index' {
  declare module.exports: any;
}

declare module 'react-bounds/modules/remarkable/remarkable' {
  declare module.exports: any;
}

declare module 'react-bounds/src/index' {
  declare module.exports: any;
}

declare module 'react-bounds/src/listener' {
  declare module.exports: any;
}

declare module 'react-bounds/src/Wrap' {
  declare module.exports: any;
}

declare module 'react-bounds/webpack.dev' {
  declare module.exports: any;
}

declare module 'react-bounds/webpack.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-bounds/build/bundle.js' {
  declare module.exports: $Exports<'react-bounds/build/bundle'>;
}
declare module 'react-bounds/docs/components/Home.jsx' {
  declare module.exports: $Exports<'react-bounds/docs/components/Home'>;
}
declare module 'react-bounds/docs/components/home/Docs.jsx' {
  declare module.exports: $Exports<'react-bounds/docs/components/home/Docs'>;
}
declare module 'react-bounds/docs/components/home/Features.jsx' {
  declare module.exports: $Exports<'react-bounds/docs/components/home/Features'>;
}
declare module 'react-bounds/docs/components/home/Footer.jsx' {
  declare module.exports: $Exports<'react-bounds/docs/components/home/Footer'>;
}
declare module 'react-bounds/docs/components/home/Header.jsx' {
  declare module.exports: $Exports<'react-bounds/docs/components/home/Header'>;
}
declare module 'react-bounds/docs/components/home/Hero.jsx' {
  declare module.exports: $Exports<'react-bounds/docs/components/home/Hero'>;
}
declare module 'react-bounds/docs/components/home/Tweet.jsx' {
  declare module.exports: $Exports<'react-bounds/docs/components/home/Tweet'>;
}
declare module 'react-bounds/docs/documentation/index.js' {
  declare module.exports: $Exports<'react-bounds/docs/documentation/index'>;
}
declare module 'react-bounds/docs/index.js' {
  declare module.exports: $Exports<'react-bounds/docs/index'>;
}
declare module 'react-bounds/examples/Box.jsx' {
  declare module.exports: $Exports<'react-bounds/examples/Box'>;
}
declare module 'react-bounds/examples/Outside.jsx' {
  declare module.exports: $Exports<'react-bounds/examples/Outside'>;
}
declare module 'react-bounds/examples/schedule/Schedule.jsx' {
  declare module.exports: $Exports<'react-bounds/examples/schedule/Schedule'>;
}
declare module 'react-bounds/examples/schedule/ScheduleItem.jsx' {
  declare module.exports: $Exports<'react-bounds/examples/schedule/ScheduleItem'>;
}
declare module 'react-bounds/gulpfile.js' {
  declare module.exports: $Exports<'react-bounds/gulpfile'>;
}
declare module 'react-bounds/lib/index.js' {
  declare module.exports: $Exports<'react-bounds/lib/index'>;
}
declare module 'react-bounds/lib/listener.js' {
  declare module.exports: $Exports<'react-bounds/lib/listener'>;
}
declare module 'react-bounds/lib/Wrap.js' {
  declare module.exports: $Exports<'react-bounds/lib/Wrap'>;
}
declare module 'react-bounds/modules/highlight.js' {
  declare module.exports: $Exports<'react-bounds/modules/highlight'>;
}
declare module 'react-bounds/modules/highlight.js/highlight.js' {
  declare module.exports: $Exports<'react-bounds/modules/highlight.js/highlight'>;
}
declare module 'react-bounds/modules/highlight.js/index.js' {
  declare module.exports: $Exports<'react-bounds/modules/highlight.js/index'>;
}
declare module 'react-bounds/modules/highlight.js/languages/javascript.js' {
  declare module.exports: $Exports<'react-bounds/modules/highlight.js/languages/javascript'>;
}
declare module 'react-bounds/modules/react-basic-layout/index.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-basic-layout/index'>;
}
declare module 'react-bounds/modules/react-basic-layout/src/components/Container.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-basic-layout/src/components/Container'>;
}
declare module 'react-bounds/modules/react-basic-layout/src/components/Grid.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-basic-layout/src/components/Grid'>;
}
declare module 'react-bounds/modules/react-docs/index.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/index'>;
}
declare module 'react-bounds/modules/react-docs/src/components/Code.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/src/components/Code'>;
}
declare module 'react-bounds/modules/react-docs/src/components/Docs.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/src/components/Docs'>;
}
declare module 'react-bounds/modules/react-docs/src/components/Markdown.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/src/components/Markdown'>;
}
declare module 'react-bounds/modules/react-docs/src/components/MarkdownTitle.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/src/components/MarkdownTitle'>;
}
declare module 'react-bounds/modules/react-docs/src/components/Sidebar.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/src/components/Sidebar'>;
}
declare module 'react-bounds/modules/react-docs/src/components/SidebarItem.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/src/components/SidebarItem'>;
}
declare module 'react-bounds/modules/react-docs/src/helpers/markdown.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-docs/src/helpers/markdown'>;
}
declare module 'react-bounds/modules/react-material-design/index.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/index'>;
}
declare module 'react-bounds/modules/react-material-design/lib/components/Link.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/lib/components/Link'>;
}
declare module 'react-bounds/modules/react-material-design/lib/components/Raised.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/lib/components/Raised'>;
}
declare module 'react-bounds/modules/react-material-design/lib/components/Tab.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/lib/components/Tab'>;
}
declare module 'react-bounds/modules/react-material-design/lib/components/Tabs.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/lib/components/Tabs'>;
}
declare module 'react-bounds/modules/react-material-design/lib/components/Tile.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/lib/components/Tile'>;
}
declare module 'react-bounds/modules/react-material-design/src/components/Link.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/src/components/Link'>;
}
declare module 'react-bounds/modules/react-material-design/src/components/Raised.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/src/components/Raised'>;
}
declare module 'react-bounds/modules/react-material-design/src/components/Tab.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/src/components/Tab'>;
}
declare module 'react-bounds/modules/react-material-design/src/components/Tabs.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/src/components/Tabs'>;
}
declare module 'react-bounds/modules/react-material-design/src/components/Tile.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-material-design/src/components/Tile'>;
}
declare module 'react-bounds/modules/react-move/index.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-move/index'>;
}
declare module 'react-bounds/modules/react-move/lib/components/Move.js' {
  declare module.exports: $Exports<'react-bounds/modules/react-move/lib/components/Move'>;
}
declare module 'react-bounds/modules/react-move/src/components/Move.jsx' {
  declare module.exports: $Exports<'react-bounds/modules/react-move/src/components/Move'>;
}
declare module 'react-bounds/modules/remarkable/index.js' {
  declare module.exports: $Exports<'react-bounds/modules/remarkable/index'>;
}
declare module 'react-bounds/modules/remarkable/remarkable.js' {
  declare module.exports: $Exports<'react-bounds/modules/remarkable/remarkable'>;
}
declare module 'react-bounds/src/index.js' {
  declare module.exports: $Exports<'react-bounds/src/index'>;
}
declare module 'react-bounds/src/listener.js' {
  declare module.exports: $Exports<'react-bounds/src/listener'>;
}
declare module 'react-bounds/src/Wrap.js' {
  declare module.exports: $Exports<'react-bounds/src/Wrap'>;
}
declare module 'react-bounds/webpack.dev.js' {
  declare module.exports: $Exports<'react-bounds/webpack.dev'>;
}
declare module 'react-bounds/webpack.prod.js' {
  declare module.exports: $Exports<'react-bounds/webpack.prod'>;
}
